name: Save the date

on:
  workflow_dispatch:

jobs:
  save-the-date:

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Save the date
        run: |
          date --utc --iso-8601=seconds > date.txt
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git diff
          git add .
          git commit -m "Save the date"
          git push

    permissions:
      contents: write
    
    runs-on: ubuntu-latest
